version: '3.8'

services:
  mcp-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-information_schema}
    depends_on:
      - mysql
    volumes:
      - .:/app
    networks:
      - mcp-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-information_schema}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  mysql-data:
